t = (7, 8, 9)
print(id(t))
t = (10, 4, 5)
print(id(t))
l = [1, 2, 3, 4]
print(id(l))
l.append(5)
print(id(l))
n_list = [1, 2, [3, 4], 5, ["welcome", "to", "class"], 9, 10]
print(n_list[-3][-1][-5])
n_list = [1, 2, 3, 4, 5, 6, 7, 8]
print(n_list[2:6])
print(n_list[::-1])
print(n_list[-1:-6])
print(n_list[-6:-1])
print(n_list[0:7:2])
print(n_list[0:8:3])
one = n_list[0:4]
two = n_list[4:]
print(one)
print(two)
n_list.extend([10])
print(n_list)
n_list.extend([10, 11, 12, 13])
print(n_list)
n_list.append([14, 15, 16])
print(n_list)
n_list.extend("tom")
print(n_list)
n_list.insert(0, 100)
print(n_list)
n_list.append("tim")
print(n_list)
n_list.insert(1, "hanks")
print(n_list)
print(n_list.pop())
print(n_list.pop(3))
n_list.clear()
print(n_list)
n_list = [1, 2, 3, 4, 5, 6, 7, 8]
print(n_list.index(2))
# print(n_list.count())
n_list = [1, 2, 3, 4, 5, 6, 7, 8, 4, 4, 4, 4, 4, 4]
print(n_list.count(4))
print(n_list.sort())
print(n_list)
n_list = [1, 2, 3, 4, 5, 6, 7, 8, 4, 4, 4, 4, 4, 4, "tom"]
# n_list.sort()
name_list = ["apple", "orange", "banana", "tamrind"]
name_list.sort()
print(name_list)
name_list.reverse()
print(name_list)
l1 = list(range(0, 5))
l2 = list(range(11, 15))
l2 = l1.copy()
print(l2)
l3 = l1
print(l3)
